// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBcobZjFFHAHLAKGWTDq5_LK1tBvqf5g',
    appId: '1:549688726450:web:bd7cbe338c076afc3d4aab',
    messagingSenderId: '549688726450',
    projectId: 'se7eti',
    authDomain: 'se7eti.firebaseapp.com',
    storageBucket: 'se7eti.firebasestorage.app',
    measurementId: 'G-L9NL2DLS7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzCgRriwPf-104hjx1gelrM8eATDRzBcU',
    appId: '1:549688726450:android:d7cef9e44fc878773d4aab',
    messagingSenderId: '549688726450',
    projectId: 'se7eti',
    storageBucket: 'se7eti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrWP_LOOv_2Zh7PwIOzTgXnXU_-j3nZQ',
    appId: '1:549688726450:ios:64d3b2be7b90a1713d4aab',
    messagingSenderId: '549688726450',
    projectId: 'se7eti',
    storageBucket: 'se7eti.firebasestorage.app',
    iosBundleId: 'com.se7eti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYrWP_LOOv_2Zh7PwIOzTgXnXU_-j3nZQ',
    appId: '1:549688726450:ios:64d3b2be7b90a1713d4aab',
    messagingSenderId: '549688726450',
    projectId: 'se7eti',
    storageBucket: 'se7eti.firebasestorage.app',
    iosBundleId: 'com.se7eti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBcobZjFFHAHLAKGWTDq5_LK1tBvqf5g',
    appId: '1:549688726450:web:2bf72d50de9a0e7a3d4aab',
    messagingSenderId: '549688726450',
    projectId: 'se7eti',
    authDomain: 'se7eti.firebaseapp.com',
    storageBucket: 'se7eti.firebasestorage.app',
    measurementId: 'G-1CP37EKJC4',
  );
}
